Show Git Prompt

diff --git a/bash/prompt b/bash/prompt
--- a/bash/prompt
+++ b/bash/prompt
@@ -1,6 +1,29 @@
 #!/bin/bash
 
+. ~/dotfiles/git/git-prompt.sh
 
+GIT_PS1_SHOWDIRTYSTATE=1
+GIT_PS1_SHOWSTASHSTATE=1
+GIT_PS1_SHOWUNTRACKEDFILES=0
+GIT_PS1_SHOWCOLORHINTS=1
+GIT_PS1_DESCRIBE_STYLE="branch"
+GIT_PS1_SHOWUPSTREAM="auto git"
 
-# Generated by http://bashrcgenerator.com
-export PS1="\$?\n\n\[$(tput sgr0)\]\[\033[38;5;10m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;11m\]\H\[$(tput sgr0)\]\[\033[38;5;15m\]: \w\n\\$ \[$(tput sgr0)\]"
+export PROMPT_COMMAND=__prompt_command  # Func to gen PS1 after CMDs
+
+function __prompt_command() {
+    local EXIT="$?"             # This needs to be first
+    PS1="\n"
+
+    local RCol='\[\e[0m\]'
+
+    local Red='\[\e[0;31m\]'
+    local Gre='\[\e[0;32m\]'
+    local BYel='\[\e[1;33m\]'
+    
+    if [ $EXIT != 0 ]; then
+        PS1+="${Red}Error Code: ${EXIT}${RCol}\n\n\n"      # Add red if exit code non 0
+    fi
+
+    PS1+="${Gre}\u@${BYel}\H: ${RCol}\w$(__git_ps1) \n${RCol}$ ${RCol}"
+}
